# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/XilinxProjects/mmult_verilog/mmult_verilog.srcs/sources_1/ip/dpram1024x64_1/dpram1024x64.xci
# IP: The module: 'dpram1024x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/mmult_verilog/mmult_verilog.srcs/sources_1/ip/dpram1024x64_1/dpram1024x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram1024x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/XilinxProjects/mmult_verilog/mmult_verilog.srcs/sources_1/ip/dpram1024x64_1/dpram1024x64.xci
# IP: The module: 'dpram1024x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/XilinxProjects/mmult_verilog/mmult_verilog.srcs/sources_1/ip/dpram1024x64_1/dpram1024x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram1024x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
